name: Iberdrola Checker

on:
  schedule:
    - cron: "*/5 * * * *"  # Cada 5 minutos
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          pip install requests beautifulsoup4

      - name: Ejecutar script
        run: python3 check_punto_carga.py
