name: Comprobación punto Iberdrola

on:
  schedule:
    - cron: '*/10 * * * *'  # Cada 10 minutos
  workflow_dispatch:        # También se puede lanzar manualmente

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script
        run: python check_punto_carga.py
